# -*- coding: utf-8 -*-
"""operadores e variaveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16D9qf5-mxfZaCMQV_sKIJ-9U9hCqZJbi
"""

# Adição
10 + 2

# Subtração
10 - 2

# Multiplicação
10 * 2

# Divisão
10 / 2

# Divisão Inteira
10 // 2

# Resto da divisão
10 % 2

# Potenciação
10 ** 2

"""#Operadores Relacionais"""

# Menor
10 < 2

# menor ou igual
10 <= 2

# Maior
10 > 2

# Maior ou igual
10 >= 2

# Igual
7 == 7

# Diferente
7 != 7

"""#Operadores lógicos

And, Or, Not

## Tabela da verdade

And
"""

print(10 > 2 and 4 < 6)        # V and V = V
print(10 > 2 and 4 > 6)        # V and F = F
print(10 < 2 and 4 < 6)        # F and V = F
print(10 < 2 and 4 > 2)        # F and F = F

"""Or"""

print(10 > 2 or 4 < 6)         # V or V = V
print(10 > 2 or 4 > 6)         # V or F = V
print(10 < 2 or 4 < 6)         # F or V = V
print(10 < 2 or 4 > 6)         # F or F = F

"""Not"""

not 10 > 2        # V = F

not 10 < 2        # F = V